In [297]:
import  torch 

In [298]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

x+y, x-y, x*y, x/y, x**y

(tensor(3.), tensor(-1.), tensor(2.), tensor(0.5000), tensor(1.))

In [299]:
x  = torch.arange(3)
x

tensor([0, 1, 2])

In [300]:
x[2]

tensor(2)

In [301]:
len(x)

3

In [302]:
x.shape

torch.Size([3])

Matrices

In [303]:
A =  torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [304]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [305]:
A = torch.tensor([[1,2,3],[2,1,2],[3,2,1]])
A == A.T     #Symmetric matrices are the subset of square matrices that are equal to their own transposes:

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Tensors

In [306]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Basic Properties of Tensor Arithmetic

In [307]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()  #Assign a copy of A to B by allocating new memory
A, A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [308]:
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [309]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, (a*X).shape    #Adding or multiplying a scalar and a tensor produces a result with the same shape as the original tensor

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

Reduction

In [310]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [311]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [312]:
A.shape, A.sum(axis=0).shape   #axis = 0 refers the rows and axis = 1 refers the columns

(torch.Size([2, 3]), torch.Size([3]))

In [313]:
A.shape, A.sum(axis=1).shape #specifying axis=1 reduces the colummn dimension by summing up elements of all the columns 

(torch.Size([2, 3]), torch.Size([2]))

In [314]:
A.sum(axis=[0,1]) == A.sum() #Reducing a matrix along both rows and columns via summation is equivalent to summing up all the elements of the matrix.

tensor(True)

In [315]:
#A.mean()
A.sum() / A.numel() #The function numel gives the number of elements in a tensor

tensor(2.5000)

In [316]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0] #A direct, built-in method that is concise and optimized
                                           #A manual way of achieving the same result

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

Non-Reduction Sum

In [317]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [318]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [319]:
A.cumsum(axis=0) #The function cumsum performs a cumulative sum over the elements of the tensor

tensor([[0., 1., 2.],
        [3., 5., 7.]])

Dot Products

In [320]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x,y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [321]:
torch.sum(x*y) #The dot product of two vectors is the sum of the products of the elements at the same position

tensor(3.)

Matrix–Vector Products

In [322]:
A.shape, x.shape, torch.mv(A,x), A@x #erforming matrix-vector multiplication

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

Matrix–Matrix Multiplication

In [323]:
B =  torch.ones(3,4)
torch.mm(A,B), A@B  #Matrix-matrix multiplication

#Matrix-Matrix Multiplication: If A and B are both 2D tensors (matrices), A @ B performs matrix-matrix multiplication.
#Matrix-Vector Multiplication: If A is a 2D tensor (matrix) and B is a 1D tensor (vector), A @ B performs matrix-vector multiplication.

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

Norms

In [324]:
u = torch.tensor([3.0, -4.0])
torch.norm(u) #The norm of a vector is a nonnegative scalar that describes the length of the vector

tensor(5.)

In [325]:
torch.abs(u).sum() #The L1 norm of a vector is the sum of the absolute values of its components                                                 

tensor(7.)

In [326]:
torch.norm(torch.ones((4,9))) #The L2 norm of a vector is the square root of the sum of the squares of the vector’s elements

tensor(6.)

Exercises

Prove that the transpose of the transpose of a matrix is the matrix itself: (AT)T = A

In [327]:
mat_A = torch.arange(6).reshape(3,2)
#mat_A

transpose_A = mat_A.T

transpose_of_transpose = transpose_A.T

print("Tensor mat_A: ", mat_A)

print("Transpose of mat_A: ", transpose_A)

print("Transpose of Transpose of mat_A: ", transpose_of_transpose)

Tensor mat_A:  tensor([[0, 1],
        [2, 3],
        [4, 5]])
Transpose of mat_A:  tensor([[0, 2, 4],
        [1, 3, 5]])
Transpose of Transpose of mat_A:  tensor([[0, 1],
        [2, 3],
        [4, 5]])


Given two matrices A and B show that sum and transposition commute: AT + BT = (A+B)T

In [328]:
M = torch.Tensor([[1,2,3],[1,1,1]])
V = torch.Tensor([[1,1,1],[1,2,3]])

print("Matrix M:", M)
print("Matrix V:", V)


M_T = M.T
V_T = V.T

print("Transpose M:", M_T)
print("Transpose V:", V_T)

sum_of_mat = (M + V)
print("Sum of the two matrices: ", sum_of_mat)

trans_sum = (M_T + V_T)
print("Sum of the trnaspose of the two matrices: ", trans_sum)

trans_of_sum = sum_of_mat.T
print("Transpose of the sum of the two: ",trans_of_sum)

Matrix M: tensor([[1., 2., 3.],
        [1., 1., 1.]])
Matrix V: tensor([[1., 1., 1.],
        [1., 2., 3.]])
Transpose M: tensor([[1., 1.],
        [2., 1.],
        [3., 1.]])
Transpose V: tensor([[1., 1.],
        [1., 2.],
        [1., 3.]])
Sum of the two matrices:  tensor([[2., 3., 4.],
        [2., 3., 4.]])
Sum of the trnaspose of the two matrices:  tensor([[2., 2.],
        [3., 3.],
        [4., 4.]])
Transpose of the sum of the two:  tensor([[2., 2.],
        [3., 3.],
        [4., 4.]])


Given any square matrix A, is A + AT(transpose) always symetric? Can you prove the result by using only the results of the previous two exercises?



In [329]:
#A = torch.tensor([[1,2],[3,4]])
A = torch.rand(2, 2)
A_T = A.T
print("Transpose of A is: ", A_T)

result = A + A_T
print("Sum of A and its transpose is: ", result)

#Now check whether the sum of A and its transpose is symmetric or not
#is_symmmetric = (result == result.T)
is_symmmetric = torch.equal(result, result.T)  #Compares two tensors element by element to check if they are exactly equal in terms of both shape and values.
print("Is the sum of A and its transpose symmetric? ", is_symmmetric)

Transpose of A is:  tensor([[0.2099, 0.9843],
        [0.9767, 0.0803]])
Sum of A and its transpose is:  tensor([[0.4198, 1.9610],
        [1.9610, 0.1605]])
Is the sum of A and its transpose symmetric?  True


We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)? Write your answer without implementing any code, then check your answer using code.

ans -> 2
The function len(X) in PyTorch (or NumPy) returns the size of the first dimension of the tensor.

In [330]:
X = torch.randn(2,3,4)
print(len(X))

2


For a tensor X of arbitrary shape, does len(X) always correspond to the length of a certain axis of X? What is that axis?

ans -> Yes, for tensor X of arbiratory shape, the output of len(X) always corresponds to the length of the first axis (axis=0) of X

the axis of a tensor are numbers starting form 0, correspondings to its dimensions
axis = 0 : first dimension 
axis = 1 : second dimension 
axis = 2 : third dimension and so on

In [331]:
#function len(X) always returns the size of axis 
X = torch.tensor([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
#X.shape
len(X)

4

Run A / A.sum(axis=1) and see what happens. Can you analyze the results?
Row-wise Sum: Each row in A is summed, producing a column vector
Element-wise Division: Each element in A is divided by the corresponding row sum This operation normalizes each row so that the sum of elements in each row becomes 1

In [332]:
A / A.sum(axis=1)

tensor([[0.1769, 0.9175],
        [0.8295, 0.0754]])

When traveling between two points in downtown Manhattan, what is the distance that you need to cover in terms of the coordinates, i.e., in terms of avenues and streets? Can you travel diagonally?

The distance between two points in terms of avenues and streets is called the Manhattan distance, and it’s calculated as the sum of the absolute differences in avenue and street coordinates:
Manhattan Distance = |Avenue2 - Avenue1| + |Street2 - Street1|

Diagonal travel is not usually possible in the strict sense within the Manhattan grid system

Consider a tensor of shape (2, 3, 4). What are the shapes of the summation outputs along axes 0, 1, and 2?

When summing a tensor along a specific axis, the resulting tensor's shape corresponds to the original shape with the summed axis removed.

Expected Output Shapes:
Axis 0: (3,4)
Axis 1: (2,4)
Axis 2: (2,3)

In [333]:
X = torch.arange(24).reshape(2,3,4)
print(X)

#when axis = 0
axis_0 = X.sum(axis=0)
print("When axis = 0: ", axis_0)

#when axis = 1
axis_1 = X.sum(axis=1)
print("When axis = 1: ", axis_1)

#when axis = 2
axis_2 = X.sum(axis=2)
print("When axis = 2: ", axis_2)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
When axis = 0:  tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])
When axis = 1:  tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])
When axis = 2:  tensor([[ 6, 22, 38],
        [54, 70, 86]])


Feed a tensor with three or more axes to the linalg.norm function and observe its output. What does this function compute for tensors of arbitrary shape?



In [334]:
Z = torch.arange(24).reshape(2,3,4).float()
print(Z)

norm_full = torch.linalg.norm(Z) #takes the square of each element and then add them all together and then take the square root of the sum
print("Full norm: ", norm_full)

norm_0 = torch.linalg.norm(Z, axis=0)
print("Norm along axis 0: ", norm_0)    

norm_1 = torch.linalg.norm(Z, axis=1)
print("Norm along axis 1: ", norm_1) 

norm_2 = torch.linalg.norm(Z, axis=2)
print("Norm along axis 2: ", norm_2) 

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
Full norm:  tensor(65.7571)
Norm along axis 0:  tensor([[12.0000, 13.0384, 14.1421, 15.2971],
        [16.4924, 17.7200, 18.9737, 20.2485],
        [21.5407, 22.8473, 24.1661, 25.4951]])
Norm along axis 1:  tensor([[ 8.9443, 10.3441, 11.8322, 13.3791],
        [28.2843, 29.9833, 31.6860, 33.3916]])
Norm along axis 2:  tensor([[ 3.7417, 11.2250, 19.1311],
        [27.0924, 35.0714, 43.0581]])
