In [70]:
import  torch 

In [71]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

x+y, x-y, x*y, x/y, x**y

(tensor(3.), tensor(-1.), tensor(2.), tensor(0.5000), tensor(1.))

In [72]:
x  = torch.arange(3)
x

tensor([0, 1, 2])

In [73]:
x[2]

tensor(2)

In [74]:
len(x)

3

In [75]:
x.shape

torch.Size([3])

Matrices

In [76]:
A =  torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [77]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [78]:
A = torch.tensor([[1,2,3],[2,1,2],[3,2,1]])
A == A.T     #Symmetric matrices are the subset of square matrices that are equal to their own transposes:

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Tensors

In [79]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Basic Properties of Tensor Arithmetic

In [80]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()  #Assign a copy of A to B by allocating new memory
A, A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [81]:
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [82]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, (a*X).shape    #Adding or multiplying a scalar and a tensor produces a result with the same shape as the original tensor

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

Reduction

In [83]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [84]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [85]:
A.shape, A.sum(axis=0).shape   #axis = 0 refers the rows and axis = 1 refers the columns

(torch.Size([2, 3]), torch.Size([3]))

In [86]:
A.shape, A.sum(axis=1).shape #specifying axis=1 reduces the colummn dimension by summing up elements of all the columns 

(torch.Size([2, 3]), torch.Size([2]))

In [87]:
A.sum(axis=[0,1]) == A.sum() #Reducing a matrix along both rows and columns via summation is equivalent to summing up all the elements of the matrix.

tensor(True)

In [88]:
#A.mean()
A.sum() / A.numel() #The function numel gives the number of elements in a tensor

tensor(2.5000)

In [89]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0] #A direct, built-in method that is concise and optimized
                                           #A manual way of achieving the same result

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

Non-Reduction Sum

In [90]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [91]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [92]:
A.cumsum(axis=0) #The function cumsum performs a cumulative sum over the elements of the tensor

tensor([[0., 1., 2.],
        [3., 5., 7.]])

Dot Products

In [93]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x,y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [94]:
torch.sum(x*y) #The dot product of two vectors is the sum of the products of the elements at the same position

tensor(3.)

Matrix–Vector Products

In [95]:
A.shape, x.shape, torch.mv(A,x), A@x #erforming matrix-vector multiplication

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

Matrix–Matrix Multiplication

In [96]:
B =  torch.ones(3,4)
torch.mm(A,B), A@B  #Matrix-matrix multiplication

#Matrix-Matrix Multiplication: If A and B are both 2D tensors (matrices), A @ B performs matrix-matrix multiplication.
#Matrix-Vector Multiplication: If A is a 2D tensor (matrix) and B is a 1D tensor (vector), A @ B performs matrix-vector multiplication.

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

Norms

In [97]:
u = torch.tensor([3.0, -4.0])
torch.norm(u) #The norm of a vector is a nonnegative scalar that describes the length of the vector

tensor(5.)

In [98]:
torch.abs(u).sum() #The L1 norm of a vector is the sum of the absolute values of its components                                                 

tensor(7.)

In [99]:
torch.norm(torch.ones((4,9))) #The L2 norm of a vector is the square root of the sum of the squares of the vector’s elements

tensor(6.)

Exercises

Prove that the transpose of the transpose of a matrix is the matrix itself: (AT)T = A

In [110]:
mat_A = torch.arange(6).reshape(3,2)
#mat_A

transpose_A = mat_A.T

transpose_of_transpose = transpose_A.T

print("Tensor mat_A: ", mat_A)

print("Transpose of mat_A: ", transpose_A)

print("Transpose of Transpose of mat_A: ", transpose_of_transpose)

Tensor mat_A:  tensor([[0, 1],
        [2, 3],
        [4, 5]])
Transpose of mat_A:  tensor([[0, 2, 4],
        [1, 3, 5]])
Transpose of Transpose of mat_A:  tensor([[0, 1],
        [2, 3],
        [4, 5]])


Given two matrices A and B show that sum and transposition commute: AT + BT = (A+B)T

In [127]:
M = torch.Tensor([[1,2,3],[1,1,1]])
V = torch.Tensor([[1,1,1],[1,2,3]])

print("Matrix M:", M)
print("Matrix V:", V)


M_T = M.T
V_T = V.T

print("Transpose M:", M_T)
print("Transpose V:", V_T)

sum_of_mat = (M + V)
print("Sum of the two matrices: ", sum_of_mat)

trans_sum = (M_T + V_T)
print("Sum of the trnaspose of the two matrices: ", trans_sum)

trans_of_sum = sum_of_mat.T
print("Transpose of the sum of the two: ",trans_of_sum)

Matrix M: tensor([[1., 2., 3.],
        [1., 1., 1.]])
Matrix V: tensor([[1., 1., 1.],
        [1., 2., 3.]])
Transpose M: tensor([[1., 1.],
        [2., 1.],
        [3., 1.]])
Transpose V: tensor([[1., 1.],
        [1., 2.],
        [1., 3.]])
Sum of the two matrices:  tensor([[2., 3., 4.],
        [2., 3., 4.]])
Sum of the trnaspose of the two matrices:  tensor([[2., 2.],
        [3., 3.],
        [4., 4.]])
Transpose of the sum of the two:  tensor([[2., 2.],
        [3., 3.],
        [4., 4.]])
